/// Flutter icons Mastermind
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Mastermind
///      fonts:
///       - asset: fonts/Mastermind.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Mastermind {
  Mastermind._();

  static const _kFontFam = 'Mastermind';
  static const String? _kFontPkg = null;

  static const IconData arrow_left = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palette = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
